/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apparriendos;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.*;
import javax.swing.table.*;
import java.io.File;
import java.util.List;
import javax.swing.JTable;
import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import java.util.ArrayList;
import javax.swing.filechooser.FileNameExtensionFilter;


import java.io.FileOutputStream;
 
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;



/**
 *
 * @author modosito
 */
public class frmReservaEquipo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReservaEquipo
     */
    public frmReservaEquipo() {
        initComponents();
        DefaultTableModel modelo =  (DefaultTableModel) jTable1.getModel();
        modelo.addColumn("NUM");
        modelo.addColumn("CODIGO");
        modelo.addColumn("DESCRIPCION");
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jButton7 = new javax.swing.JButton();
        cboxAdmin = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboxInstalador = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtCelular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dtpFecha = new datechooser.beans.DateChooserCombo();
        dtpFechaTermino = new datechooser.beans.DateChooserCombo();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        chHora = new java.awt.Choice();
        chHora2 = new java.awt.Choice();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apparriendos/edit-clear.png"))); // NOI18N
        jButton7.setText("LIMPIAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setText("ADMINISTRATIVO");

        jLabel4.setText("INSTALADOR");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel5.setText("CODIGO");

        jLabel6.setText("DESCRIPCION");

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apparriendos/tick.png"))); // NOI18N
        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("TELEFONO");

        jLabel10.setText("CELULAR");

        jLabel7.setText("RUT CLIENTE");

        txtTelefono.setEnabled(false);

        jLabel8.setText("NOMBRE");

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\modosito\\Desktop\\edit-clear.png")); // NOI18N
        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtCelular.setEnabled(false);

        jLabel11.setText("EMAIL");

        jLabel1.setText("FOLIO");

        txtEmail.setEnabled(false);

        txtFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFolioActionPerformed(evt);
            }
        });

        jLabel2.setText("FECHA");

        jLabel12.setText("FECHA TERMINO");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apparriendos/add.png"))); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apparriendos/edit-clear.png"))); // NOI18N
        jButton4.setText("LIMPIAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane2.setViewportView(txtObservacion);

        jLabel13.setText("OBSERVACION");

        jLabel14.setText("HORA SALIDA");

        jLabel15.setText("HORA ENTREGA");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apparriendos/system-search-32.png"))); // NOI18N
        jButton5.setText("BUSCAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apparriendos/system-search-32.png"))); // NOI18N
        jButton6.setText("BUSCAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apparriendos/export_excel.png"))); // NOI18N
        jButton8.setText("EXPORTAR EXCEL");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apparriendos/document_delete.png"))); // NOI18N
        jButton9.setText("ANULAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEstado.setText("NUEVO");

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apparriendos/pdf.png"))); // NOI18N
        jButton10.setText("EXPORTAR A PDF");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addGap(140, 140, 140)
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxInstalador, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(52, 52, 52))
                                    .addComponent(txtFolio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10)
                                            .addComponent(txtNombre)
                                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(159, 159, 159)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton7))
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))))))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(chHora, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(dtpFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtpFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtpFechaTermino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxInstalador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(jButton10))
                        .addComponent(jButton1)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9)
                        .addComponent(lblEstado)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LimpiarProducto();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      try
      {
  if(txtCodigo.getText().trim().isEmpty())
         {
               JOptionPane.showMessageDialog(this, "Debe seleccionar item a agregar"); 
         }else
         {
             // AgregarItem();
              DefaultTableModel modelo =  (DefaultTableModel) jTable1.getModel();
              int numRow= jTable1.getRowCount();
              if(numRow == 0)
              {
                  numRow = 1;
              }else{
                  numRow= jTable1.getRowCount() + 1;
              }
              
                     Connection miConexion=(Connection) Conexion.GetConnection();              
                     Statement statement=(Statement) miConexion.createStatement();
                     String producto = txtCodigo.getText();
                     ResultSet rs = statement.executeQuery("SELECT COUNT(*) AS num FROM tb_articulo WHERE codigo ='"+ producto +"' AND disponible = 1 ");
                     int rows= 0;
                     if(rs.next()){
                         rows = rs.getInt("num");
                     } 
              
                     if(rows == 0)
                     {
                         modelo.addRow(new Object[]{numRow, txtCodigo.getText(), txtDescripcion.getText()});
                         LimpiarProducto();                          
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(this, "ARTICULO SELECCIONADO NO DISPONIBLE"); 
                     }
              


         }         
      }
      catch (Exception ex)
      {
         JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
      } 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
         if(txtCodigo.getText().trim().isEmpty())
         {
             JOptionPane.showMessageDialog(this, "Debe seleccionar item a agregar"); 
         }else
         {
         
             try
             {
                  ResultSet rs = null;
                  Connection miConexion=(Connection) Conexion.GetConnection();
                  Statement statement=(Statement) miConexion.createStatement();
                  String codigo = txtCodigo.getText();
                  rs = statement.executeQuery("SELECT * from tb_articulo where codigo = '"+ codigo +"'");
             
                  while(rs.next()){
                 
                     txtCodigo.setText(rs.getString("codigo"));
                     txtDescripcion.setText(rs.getString("descripcion"));

                  }
             
                  miConexion.close();
             }
             catch (Exception ex)
             {
                //JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
             }            
         }
        
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
        
          if(txtRut.getText().trim().isEmpty())
         {
             JOptionPane.showMessageDialog(this, "Debe seleccionar item a agregar"); 
         }else
         {
         
             try
             {
                  ResultSet rs = null;
                  Connection miConexion=(Connection) Conexion.GetConnection();
                  Statement statement=(Statement) miConexion.createStatement();
                  String rut = txtRut.getText();
                  rs = statement.executeQuery("SELECT * from tb_cliente where rut = '"+ rut +"'");
             
                  while(rs.next()){
                 
                     txtRut.setText(rs.getString("rut"));
                     txtNombre.setText(rs.getString("nombre"));
                     txtTelefono.setText(rs.getString("telefono"));
                     txtCelular.setText(rs.getString("celular"));
                     txtEmail.setText(rs.getString("email"));
                  
                  }
             
                  miConexion.close();
             }
             catch (Exception ex)
             {
                //JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
             }            
         }       
        
    }//GEN-LAST:event_txtRutActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        txtRut.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtCelular.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
         String[ ] hora = {
             "08:00",
             "08:30",
             "09:00",
             "09:30",
             "10:00",
             "10:30",
             "11:00",
             "11:30",
             "12:00",
             "12:30",
             "13:00",
             "13:30",
             "14:00",
             "14:30",
             "15:00",
             "15:30",
             "16:00",
             "16:30",
             "17:00",
             "17:30",
             "18:00",
             "18:30",
             "19:00",
             "19:30",
             "20:00",
             "20:30",
             "21:00",
             "21:30",
             "22:00",
             "22:30",
             "23:00",
             "23:30",
             "24:00"
         };
        
         for (int i = 0 ; i < hora.length ; i++) {
            chHora.add(hora[i]);
            chHora2.add(hora[i]);
         }
        cargarlista();
        ObtenerFolio();
    }//GEN-LAST:event_formInternalFrameOpened

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        Connection miConexion=(Connection) Conexion.GetConnection();
        try
        {
            int fila = jTable1.getRowCount();
            if(txtRut.getText().trim().isEmpty())
            {
               JOptionPane.showMessageDialog(this, "Debe ingresar campo rut"); 
            }
            else if(fila == 0){
                JOptionPane.showMessageDialog(this, "Debe asociar items a grilla");                
            }
            else
            {
 
                 Statement statement=(Statement) miConexion.createStatement();

                 ObtenerFolio();
                 String fecha = dtpFecha.getText();
                 String fechaT = dtpFechaTermino.getText();
                 String hora = chHora.getSelectedItem();
                 String horaT = chHora2.getSelectedItem();
                 String rut = txtRut.getText();
                 String observacion = txtObservacion.getText();
                 int folio = Integer.parseInt(txtFolio.getText());
                 String admin = cboxAdmin.getSelectedItem().toString();
                 String insta = cboxInstalador.getSelectedItem().toString();
                       
                 statement.execute("insert into tb_reserva (num, fecha, fecha_entrega, hora, hora_entrega, rut, observacion, cod_admin, cod_instalador, estado) values('"+folio+"','"+fecha+"','"+fechaT+"','"+hora+"','"+horaT+"','"+rut+"', '"+ observacion +"', '"+ admin +"', '"+ insta +"', 1)");
                    
                       for(int i=0;i<jTable1.getRowCount();i++)
                       {
                             int num= (int)jTable1.getValueAt(i,0);
                             String cod= (String)jTable1.getValueAt(i,1);
                             String des= (String)jTable1.getValueAt(i,2);
                             statement.execute("insert into tb_reserva_detalle values('"+folio+"','"+num+"','"+cod+"','"+des+"')");
                             statement.execute("update tb_articulo set disponible = 1 where codigo = '"+ cod +"' ");
                       }
                    
                    JOptionPane.showMessageDialog(this, "Datos ingresados correctamente");
                   Limpiar();
                     statement.close();
                     miConexion.close();                
                 
                
            }

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Limpiar();
        ObtenerFolio();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        frmClienteBusca frm = new frmClienteBusca();
        frmPanelAdministrativo.desktopPane.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        frmArticuloBusca frm = new frmArticuloBusca();
        frmPanelAdministrativo.desktopPane.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFolioActionPerformed
        // TODO add your handling code here:
          Connection miConexion=(Connection) Conexion.GetConnection();
        try
        {
            if(txtFolio.getText().trim().isEmpty())
            {
               JOptionPane.showMessageDialog(this, "Debe ingresar campo numero de folio"); 
            }
            else
            {
 
                 Statement statement=(Statement) miConexion.createStatement();
                 String folio = txtFolio.getText();

                 ResultSet rs = statement.executeQuery("SELECT COUNT(*) AS num FROM tb_reserva WHERE num ='"+ folio +"' ");
                 int rows= 0;
                 if(rs.next()){
                     rows = rs.getInt("num");
                 }
            
                 if(rows > 0)
                 {                
                      rs = statement.executeQuery("SELECT * FROM tb_reserva WHERE num ='"+ folio +"' ");
   
                     while(rs.next()){
            
                        txtObservacion.setText(rs.getString("observacion"));
                        txtRut.setText(rs.getString("rut"));
                        
                        ObtenerRegistroCliente(rs.getString("rut"));
                        
                        dtpFecha.setText(rs.getString("fecha"));
                        dtpFechaTermino.setText(rs.getString("fecha_entrega"));
                        
                        chHora.select(rs.getString("hora"));
                        chHora2.select(rs.getString("hora_entrega"));
                        
                        int estado = rs.getInt("estado");
                        switch(estado){
                            case 1:
                                  lblEstado.setText("EMITIDO");
                                break;
                             case 2:
                                  lblEstado.setText("ANULADO");
                                break;
                             case 3:
                                  lblEstado.setText("EJECUTADO");
                                break;                               
                        }
                                    DefaultTableModel modelo =  (DefaultTableModel) jTable1.getModel();
                        rs = statement.executeQuery("SELECT * FROM tb_reserva_detalle WHERE folio ='"+ folio +"' ");
          for (int i = 0; i < jTable1.getRowCount(); i++) {
           modelo.removeRow(i);
           i-=1;
       }
                        while(rs.next())
                        {
                            

                            modelo.addRow(new Object[]{rs.getString("codigo"), rs.getString("descripcion")});
                    
                        }
        
                     }    
                     rs.close();
                     
                     statement.close();
                     miConexion.close();     
                 }
                 else
                 {           
                      JOptionPane.showMessageDialog(this, "Numero de folio ingresado no se encuentra en sistema");                
                 }
                
            }

        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }
    }//GEN-LAST:event_txtFolioActionPerformed

      private void ObtenerRegistroCliente(String rut){
        
        try
        {
             ResultSet rs, rs2 = null;
             Connection miConexion=(Connection) Conexion.GetConnection();
             Statement statement=(Statement) miConexion.createStatement();
             rs = statement.executeQuery("SELECT * from tb_cliente where rut = '"+ rut +"'");
             
             while(rs.next())
             {                 
                 txtRut.setText(rs.getString("rut"));
                 txtNombre.setText(rs.getString("nombre"));
                 txtTelefono.setText(rs.getString("telefono"));
                 txtCelular.setText(rs.getString("celular"));
                 txtEmail.setText(rs.getString("email"));
             }
             
             miConexion.close();
        }
        catch (Exception ex)
        {
            //JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }

    }
    
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    // TODO add your handling code here:
        if (this.jTable1.getRowCount()==0) {
            JOptionPane.showMessageDialog (null, "No hay datos en la tabla para exportar.","BCO",
                JOptionPane.INFORMATION_MESSAGE);

            return;
        }
        JFileChooser chooser=new JFileChooser();
        FileNameExtensionFilter filter=new FileNameExtensionFilter("Archivos de excel","xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar archivo");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
            List<JTable> tb=new ArrayList<>();
            List<String>nom=new ArrayList<>();
            tb.add(jTable1);
            nom.add("Detalle de Gastos");
            String file=chooser.getSelectedFile().toString().concat(".xls");
            try {
                Exporter e=new Exporter(new File(file),tb, nom);
                if (e.export()) {
                    JOptionPane.showMessageDialog(null, "Los datos fueron exportados a excel.","BCO",
                        JOptionPane.INFORMATION_MESSAGE);

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Hubo un error"+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
                  Connection miConexion=(Connection) Conexion.GetConnection();
        try
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "¿ DESEA ANULAR DOCUMENTO ?", "RESERVAS", dialogButton);
            if(dialogResult == 0) 
            {
                 if(txtFolio.getText().trim().isEmpty())
                 {
                     JOptionPane.showMessageDialog(this, "Debe ingresar campo numero de folio"); 
                 }
                 else
                 {
                     Statement statement=(Statement) miConexion.createStatement();
                     String folio = txtFolio.getText();
                     ResultSet rs = statement.executeQuery("SELECT COUNT(*) AS num FROM tb_reserva WHERE num ='"+ folio +"' ");
                     int rows= 0;
                     if(rs.next()){
                         rows = rs.getInt("num");
                     }          
                     if(rows > 0)
                     {                
                         int cantidad = statement.executeUpdate("UPDATE tb_reserva SET estado = 2 WHERE num ='"+ folio +"' ");
                         if(cantidad > 0)
                         {
                             JOptionPane.showMessageDialog(this, "Registro ANULADO exitosamente");
                             Limpiar();
                         }
                         else
                         {
                             JOptionPane.showMessageDialog(this, "Problema ANULANDO registro de sistema");
                         }      
                     }
                     else
                     {           
                         JOptionPane.showMessageDialog(this, "Numero de folio ingresado no se encuentra en sistema");                
                     }
                
                 }
            } 
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try
        {
         Connection miConexion=(Connection) Conexion.GetConnection();
         Statement statement=(Statement) miConexion.createStatement();
         String folio = txtFolio.getText();         
         ResultSet rs = statement.executeQuery("SELECT COUNT(*) AS num FROM tb_reserva WHERE num ='"+ folio +"' ");
         int rows= 0;
         if(rs.next()){
           rows = rs.getInt("num");
         }
         
         if(rows > 0)
         {   
             JFileChooser chooser=new JFileChooser();
             FileNameExtensionFilter filter=new FileNameExtensionFilter("Documento Pdf","pdf");
             chooser.setFileFilter(filter);
             chooser.setDialogTitle("Guardar archivo");
             chooser.setMultiSelectionEnabled(false);
             chooser.setAcceptAllFileFilterUsed(false);
             if (chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION)
             {

                 String file=chooser.getSelectedFile().toString().concat(".pdf");
                 FileOutputStream archivo = new FileOutputStream(file);
                 Document documento = new Document();
                 PdfWriter.getInstance(documento, archivo);
                 documento.open();
                                
                 documento.add(new Paragraph("DOCUMENTO RESERVA",new Font(Font.FontFamily.HELVETICA,20)));
                 documento.add(new Paragraph(""));
                 documento.add(new Paragraph(""));
                 documento.add(new Paragraph("Número de folio : " + folio));
                 documento.add(new Paragraph(""));
                 rs = statement.executeQuery("SELECT * FROM tb_reserva WHERE num ='"+ folio +"' ");  
                 while(rs.next())
                 {              
                     documento.add(new Paragraph("Pedido Para Dia : " + rs.getString("fecha")+ " A Las : " + rs.getString("hora") + "  Horas"));
                     documento.add(new Paragraph("Devolucion De Pedido Para El Dia : " + rs.getString("fecha_entrega") + " A Las : " + rs.getString("hora_entrega") + "  Horas"));
                     documento.add(new Paragraph("Solicitó : " + rs.getString("rut")));
                     documento.add(new Paragraph("Fue Atendido Por : " + rs.getString("cod_admin")));
                     documento.add(new Paragraph("Sera Instalado Por : " + rs.getString("cod_instalador")));
                     
                        
                     int estado = rs.getInt("estado");
                     switch(estado)
                     {
                         case 1:
                             documento.add(new Paragraph("ESTADO : EMITIDO"));
                             break;
                         case 2:
                             documento.add(new Paragraph("ESTADO : ANULADO"));
                             break;
                         case 3:
                             documento.add(new Paragraph("ESTADO : EJECUTADO"));
                             break;                               
                     }
                     
                     documento.add(new Paragraph("OBSERVACION : " + rs.getString("observacion"),new Font(Font.FontFamily.HELVETICA,14)));
                 }  
                 
                 
                 
                 PdfPTable table = new PdfPTable(3);                

                 rs = statement.executeQuery("SELECT * FROM tb_reserva_detalle WHERE folio ='"+ folio +"' ");
                 
                 table.addCell("LINEA");
                 table.addCell("CODIGO");
                 table.addCell("DESCRIPCION");
                 while(rs.next())
                 {
                     table.addCell(rs.getString("num"));
                     table.addCell(rs.getString("codigo"));
                     table.addCell(rs.getString("descripcion"));
                    
                 }
              
                 documento.add(new Paragraph(" "));
                 documento.add(new Paragraph(" "));
                 documento.add(new Paragraph(" Equipos Solicitados : ", new Font(Font.FontFamily.HELVETICA,14)));
                 documento.add(new Paragraph(" "));
                 documento.add(table);
                 
                
                 
             
                 documento.close();   
             } // fin saveshowdialog                    
         }
         else
         {
             JOptionPane.showMessageDialog(this, "Numero de folio ingresado no se encuentra en sistema");    
         }
         
       
        
        } // fin trycatch
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void Limpiar()
    {
        dtpFecha.setText("");
        dtpFechaTermino.setText("");
        chHora.select(0);
        chHora2.select(0);
      
        txtRut.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtCelular.setText("");
        txtEmail.setText("");
        txtObservacion.setText("");
        txtCodigo.setText("");
        txtDescripcion.setText("");
        lblEstado.setText("NUEVO");
        
        DefaultTableModel modelo =  (DefaultTableModel) jTable1.getModel();

       for (int i = 0; i < jTable1.getRowCount(); i++) {
           modelo.removeRow(i);
           i-=1;
       }
       


    }
    
    private void ObtenerFolio()
    {
        Connection miConexion=(Connection) Conexion.GetConnection();
        try
        {

                 Statement statement=(Statement) miConexion.createStatement();
                 ResultSet rs = statement.executeQuery("SELECT COUNT(*) AS num FROM tb_reserva ");
                 int rows= 0;
                 if(rs.next()){
                     rows = rs.getInt("num");
                 }
            
                 if(rows > 0)
                 {                    
                     rs = statement.executeQuery("SELECT MAX(num) + 1 as num from tb_reserva");  
                     while(rs.next()){                
                          rows = rs.getInt("num");    
                     }
                         
                 } else{
                     rows = 1;
                 }      
                 
             txtFolio.setText(Integer.toString(rows));
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ex.getMessage());
        }        
    }
    
    
    private void cargarlista() 
    {
   
       try {
             ResultSet rs = null;
             Connection miConexion=(Connection) Conexion.GetConnection();
             Statement statement=(Statement) miConexion.createStatement();  
              rs = statement.executeQuery ("SELECT * FROM tb_administrador WHERE tipo_usuario = 2");

            while(rs.next()){
               String tmpStrObtenido = rs.getString("nombre");
               cboxAdmin.addItem(tmpStrObtenido);
               
             }
            
            
             rs = statement.executeQuery ("SELECT * FROM tb_administrador WHERE tipo_usuario =3");

            while(rs.next()){
               String tmpStrObtenido = rs.getString("nombre");
               cboxInstalador.addItem(tmpStrObtenido);
             }
             miConexion.close();
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Error "+ ex.getMessage());
        }        
                    
    }
    
 
 void fillData(JTable table, File file) {
 
  try {
      
 
    //Desktopane.getDesktop().open(path); 
    WritableWorkbook workbook1 = Workbook.createWorkbook(file); 
    WritableSheet sheet1 = workbook1.createSheet("First Sheet", 0);
    TableModel model = table.getModel();
   
 
    for (int i = 0; i < model.getColumnCount(); i++) {
      Label column = new Label(i, 0, model.getColumnName(i));
      sheet1.addCell(column);
    }
 
    int j = 0;
    for (int i = 0; i < model.getRowCount(); i++) {
      for (j = 0; j < model.getColumnCount(); j++) {
        Label row = new Label(j, i + 1,
        model.getValueAt(i, j).toString());
        sheet1.addCell(row);
   }
  }
 
  workbook1.write();
  workbook1.close();
 
  } catch (Exception ex) {
     JOptionPane.showMessageDialog(null, "Error creating Excel file.");
     ex.printStackTrace();
  }
}

    
    
    
    private void LimpiarProducto(){
    
        txtCodigo.setText("");
        txtDescripcion.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxAdmin;
    private javax.swing.JComboBox<String> cboxInstalador;
    private java.awt.Choice chHora;
    private java.awt.Choice chHora2;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserCombo dtpFecha;
    private datechooser.beans.DateChooserCombo dtpFechaTermino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEstado;
    public static javax.swing.JTextField txtCelular;
    public static javax.swing.JTextField txtCodigo;
    public static javax.swing.JTextField txtDescripcion;
    public static javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFolio;
    public static javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObservacion;
    public static javax.swing.JTextField txtRut;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
